[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.19.0"
  NPM_VERSION = "10.9.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable settings for build
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
